[project]
name = "robostack"
version = "0.1.0"
description = "Development environment for RoboStack ROS packages"
authors = ["kobayashilab <admin@hci.ics.saitama-u.ac.jp>"]
channels = ["https://fast.prefix.dev/conda-forge"]
# platforms = ["linux-64", "win-64", "osx-64", "osx-arm64", "linux-aarch64"]
platforms = ["linux-64"]

# [target.win-64.dependencies]
# vs2022_win-64 = "*"  # Uncomment if using Visual Studio 2022

[dependencies]
python = "*"
compilers = "*"
cmake = "==3.31"
pkg-config = "*"
make = "*"
ninja = "*"
gstreamer = ">=1.24.7,<2"

[target.linux.dependencies]
libgl-devel = "*"

[environments]
noetic = { features = ["noetic"] }
humble = { features = ["humble"] }
jazzy = { features = ["jazzy"] }

# noetic
[feature.noetic]
channels = ["https://prefix.dev/robostack-noetic"]

[feature.noetic.dependencies]
ros-noetic-desktop = "*"
catkin_tools = "*"
rosdep = "*"

# humble
[feature.humble]
channels = ["https://prefix.dev/robostack-humble"]

[feature.humble.dependencies]
ros-humble-desktop = "*"
colcon-common-extensions = "*"
rosdep = "*"

# jazzy
[feature.jazzy]
channels = ["https://prefix.dev/robostack-jazzy"]

[feature.jazzy.dependencies]
ros-jazzy-desktop = "*"
colcon-common-extensions = "*"
rosdep = "*"
